<?php

namespace Blogger\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CancionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CancionesRepository extends EntityRepository
{
	public function findByPortadaCanciones($limit = null)
	{
		$qp = $this->createQueryBuilder('c')->select('c')->addGroupBy('c.interprete_id');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}

	public function getLatestCanciones($limit = null)
	{
		$qp = $this->createQueryBuilder('c')->select('c')->addOrderBy('c.puesto_ranking', 'DESC');

		if (false === is_null($limit))
			$qp->setMaxResults($limit);

		return $qp->getQuery()->getResult();
	}

	public function getCancionesForEstilo($estiloId)
	/*DAME TODOS LOS COMENTARIOS DE UN POST*/
	{
		$qp = $this->createQueryBuilder('c')->select('c')->where('c.estilos = :estilos')->setParameter('estilos', $estiloId);


		return $qp->getQuery()->getResult();
	}
}
